#!/bin/sh
BKLIST=sda
while inotifywait -e create /dev/ --include sd[a-z][1-9];
do
	DISKNAME=$(lsblk -r --output name,mountpoint,type | grep  sd |grep  'part' | grep -v $BKLIST |grep -v '/'|cut -f 1,2 -d ' ' | dmenu -b -p "mount:")
	DISK=/dev/$DISKNAME
	if [ "$DISK" != "/dev/" ];then
		LOC=$(echo ' ' |dmenu -b -p "mount point(Default /mnt)")
		if [ "$LOC" == " " ];then
			LOC=/mnt/$DISKNAME
		fi
		sudo mkdir -p $LOC
		sudo mount $DISK $LOC;
	fi
done
