#!/bin/sh
if [ "$1" == "-b" ];
then
	while :
	do
		sleep $2;sudo bash -c"echo 2 > /proc/acpi/ibm/kbdlight"
		sleep $2;sudo bash -c"echo 1 > /proc/acpi/ibm/kbdlight"
	done
fi
sudo bash -c"echo "$1" > /proc/acpi/ibm/kbdlight"
