#!/bin/sh
if [ "$1" == "-b" ];
then
	while :
	do
		sleep $2;sudo -u root echo 2 > /proc/acpi/ibm/kbdlight
		sleep $2;sudo -u root echo 1 > /proc/acpi/ibm/kbdlight
	done
fi
sudo -u root $1 > /proc/acpi/ibm/kbdlight
